name: pelusodan_dev
description: Personal website written in Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.6.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.1
  font_awesome_flutter: ^9.1.0
  animated_background: ^2.0.0
  flutter95: ^1.0.0
  flutter_form_builder: ^9.1.1
  timelines: ^0.1.0
  url_launcher: ^6.1.5
  email_validator: ^2.1.16
  http: ^1.0.0
  syncfusion_flutter_pdfviewer: ^22.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/img/old_school_profile.jpg
    - assets/img/header_dan.png
    - assets/img/wallet_guru.png
    - assets/img/feed.png
    - assets/img/cv.png
    - assets/img/austin.png
    - assets/img/mature.png
    - assets/img/neu.png
    - assets/img/pison.png
    - assets/img/whoop.png
    - assets/img/fridgePal.png
    - assets/img/kanestheticLearning.png
    - assets/img/missMyTrain.png
    - assets/img/pokemon.png
    - assets/img/walletGuru.png
    - assets/doc/resume.pdf
    - assets/img/daffy.gif
    - assets/img/peloton.png
    - assets/img/droidcon.jpg
    - assets/img/flutterWeb.jpg
    - assets/img/droidcon2.jpg
    - assets/img/klaviyo.png
  fonts:
    - family: Blockstepped
      fonts:
        - asset: fonts/Blockstepped.ttf
